export enum EstadosComponenteListadoUsuarios {

    INICIAL,
    ERROR,
    REALIZANDO_CARGA,
    NORMAL,
    ALGUN_USUARIO_SELECCIONADO,
    TODOS_USUARIOS_SELECCIONADOS,
    USUARIO_EN_EDICION,
    USUARIO_EN_BORRADO
}